name: MarkBind Action

on:
  push:
    branches:
      - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: MarkBind/markbind-action@release/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          baseUrl: '/animal-behaviour-LSM1303'
          version: '3.1.1'